// <auto-generated />
namespace FantasyWatch.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedleaguemodelfixedplayer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedleaguemodelfixedplayer));
        
        string IMigrationMetadata.Id
        {
            get { return "201703091516364_added league model, fixed player"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
